### ISSUE TITLE
Support IE8 by default

### ISSUE THREAD

**Issue by blond** [bem/project-stub#105]
See https://ru.bem.info/forum/issues/358/

**Comment by tadatuta** [comment]
смотрю в статистику и вангую won't fix этому issue

**Comment by sipayRT** [comment]
а зачем по умолчанию это делать? собирается лишний файл, которы может и не понадобиться. Вот если бы в генератор такое запилить, то смысл был бы...

**Comment by blond** [comment]
> смотрю в статистику и вангую won't fix этому issue

Странно хотеть этого в `bem-*` библиотеках, и не хотеть в коробке. Вреда вроде бы нет :)

> собирается лишний файл, которы может и не понадобиться. 

Никто особо не заметит, что собрался лишний файл :)

**Comment by tadatuta** [comment]
> Странно хотеть этого в bem-* библиотеках, и не хотеть в коробке. Вреда вроде бы нет :)

оно потому и в `bem-components` сделано опционально, что далеко не всем нужно. ну и в компонентах мы это поддержали в первую очередь для одной конкретной компании, которая вряд ли активно использует `project-stub` ;)

**Comment by blond** [comment]
Тогда давайте в README напишем список поддерживаемых бразуеров, и куда идти (в генератор) если нужен IE8.

**Comment by sipayRT** [comment]
:+1:
