### ISSUE TITLE
Broken on windows 7

### ISSUE THREAD

**Issue by apsavin** [bem/project-stub#110]
I just did the steps from the README.md and...

![2015-05-24 11 52 17](https://cloud.githubusercontent.com/assets/632171/7787266/c6252212-020b-11e5-973d-e1b123117089.png)

`enb make` was ended without any error though.

**Comment by levonet** [comment]
We won't support bem-tools on windows.

**Comment by apsavin** [comment]
I think, it should be mentioned in the README.

> Git Bash if you use Windows OS.

This makes people think that all should work.

**Comment by tadatuta** [comment]
@apsavin actually we're going to replace `bem make` with `enb make` inside `bem-tools`

**Comment by apsavin** [comment]
@tadatuta good news. And `bem server` with `enb server`, I suppose?
But I think, we should change the README.md anyway. I don't think that this changes inside bem-tools will be in near future.

**Comment by tadatuta** [comment]
yeah, sure
