### ISSUE TITLE
Не работают зависимости для js технологии

### ISSUE THREAD

**Issue by blond** [bem/project-stub#111]
Если подключить `textarea`, то не весь необходимый JavaScript приедет.

Подробнее:
https://github.com/bem/bem-components/blob/v2/common.blocks/textarea/textarea.deps.js#L10-L13

**Comment by tadatuta** [comment]
Я все еще хочу https://github.com/enb-bem/enb-bem-techs/issues/120

**Comment by Guria** [comment]
А я предлагаю не экономить на спичках (29 строк шаблонов) и в рамках bem/bem-components#1565 сделать обычную зависимость блока `textarea` от блока `input` и избавиться от избыточного шага в сборке.

**Comment by blond** [comment]
Решили в https://github.com/bem/bem-components/pull/1571
