### ISSUE TITLE
Cannot find module 'bemhtml-compat'

### ISSUE THREAD

**Issue by voischev** [bem/project-stub#115]
```
git clone ...
npm i
bem create -b test -l desktop.blocks -T bemhtml
```

**Comment by tadatuta** [comment]
есть такая проблема. пакеты нужны для `bem make`, но `require` общий :(
пока предлагаю ставить локально, а я подумаю что с этим сделать малой кровью (пока склоняюсь к тому, чтобы положить технологии прямо в `project-stub`, где будет только про `bem create`, заодно и чуть причешу их).

**Comment by voischev** [comment]
может в `bem-tools` положить все-таки? А то что это `bem-tools` вне стаба не получится использовать?

**Comment by tadatuta** [comment]
@voischev они и сейчас не в `bem-tools` лежат, а в `bem-core`
