### ISSUE TITLE
Conflict with nginx installed via homebrew

### ISSUE THREAD

**Issue by h4** [bem/project-stub#131]
I cloned project-stub, installed npm deps and run server. But suddenly I got this error:

```bash
⇒  npm start

> bem-project-stub@1.4.0 start /Users/h4/Projects/my-bem-project
> enb server

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
```

After short investigation I realise that nginx was installed via Homebrew and listen port 8080 by default.

Maybe we should add short note into Readme that explains how to change default port used by ENB?

**Comment by blond** [comment]
> Maybe we should add short note into Readme that explains how to change default port used by ENB?

@tadatuta let's add something like:

```
$ npm start -- --port=8181
```

**Comment by tadatuta** [comment]
@h4, @blond Done.
Thank you for report and `--` :)

**Comment by blond** [comment]
@tadatuta what about [README.ru.md](https://github.com/bem/project-stub/blob/bem-core/README.ru.md)?
