### ISSUE TITLE
Не создаются модификаторы у елементов

### ISSUE THREAD

**Issue by UsenkoJaroslav** [bem/project-stub#149]
Не создаются модификаторы у елементов. У блоков работают.

**Comment by tadatuta** [comment]
Можно чуть подробнее описать проблему?

**Comment by UsenkoJaroslav** [comment]
В версии 1.6.0 когда пишу { elem: 'some-element', mods: { theme: 'some-theme' } } после сборки в html  нет .some-element_theme_some-theme.
В 1.5.0 все нормально

**Comment by awinogradov** [comment]
mods -> elemMods

**Comment by UsenkoJaroslav** [comment]
Зачем такое переименование?

**Comment by awinogradov** [comment]
Кажется так всегда и было, просто шаблонизатор выполнял некую магию, которую ныне упразднили. https://ru.bem.info/technology/bemjson/v2/bemjson/#Представление-БЭМ-сущностей

**Comment by tadatuta** [comment]
Да, это исправление старой проблемы. Оно позволяет в шаблонах писать предикаты про модификатор блока и про модификатор элемента одновременно.

**Comment by UsenkoJaroslav** [comment]
Спасибо!
