### ISSUE TITLE
project-stub@v2

### ISSUE THREAD

**Issue by belozyorcev** [bem/project-stub#156]
Всем привет. 

В общем хочется процветания БЭМ во всех его направлениях. Хочу оставить несколько идей для голосования сообщества (ну и чтобы сообщество тоже предложило свои идеи для голосования).

За время жизни `project-stub` накопилось много моментов, которые так или иначе привлекают или отталкивают людей. А т.к. `project-stub` - это практически лицо БЭМ, хочется чтобы оно было максимально дружелюбным.

Записи оставлять по следующему формату:

## Заголовок идеи 

Описание почему и зачем.

П.Н.
(заголовок второго уровня `##`)

**Comment by belozyorcev** [comment]
## Переименовать project-stub в bem-starter-kit

Для многих `starter-kit` даёт точное описание того, что несёт в себе данное название. Я когда впервые объяснял на студии про `project-stub` на меня смотрели с недоумением. Что ещё это за штука такая? Зачем ставить какой-то `project-stub`?

**Comment by belozyorcev** [comment]
## \*.blocks -> blocks/\*

Часто видно в проектах, что люди предпочитают именно такой стиль расположения блоков. Он добавляет один уровень иерархии, но при этом визуально выглядит намного аккуратней.

```
common.blocks
desktop.blocks
desing.blocks
```

```
blocks/common
blocks/desktop
blocks/desing
```

также история и с *bundles.

**Comment by belozyorcev** [comment]
## bemtree вместо bemjson (по-умолчанию)

С этой проблемой столкнулся лично я. С одной стороны выглядит безумием, а с другой оправданно. Когда я начинал своё знакомство, то городил длиннющий `bemjson`. Это ад! Я проклинал БЭМ, но верил в него. Городил различные `require` для подставки кусков bemjson. Кто работал с большим уровне вложенности блоков, тот поймёт. Это страшно. Затем начинает болеть голова... Как ЭТО ВСЁ ВНЕДРИТЬ В ПРОЕКТ, как это вообще можно контролировать, ГДЕ ХВАЛЁННАЯ ПРОСТОТА БЭМ?? Слышал про `bemtree`, но как его использовать? Я тут только городить иерархию научился. Это ещё сложнее будет, не зря ведь для более опытных оставляют!

Сверстать что-то только на BEMJSON, достаточно трудно. И тем более это отредактировать потом. Потом мне пришлось искать bemtree, т.к. это было единственным решением, которое я видел. И ОПА! Приплыли! Теперь нужно ещё deps файлы прописывать, а то сборка чёт не собирается.

Почему бы не прививать bemtree сразу, если дело к нему идёт в конечном итоге? Человек уже на первых этапах будет знать,  что нужно для того, чтобы собирать проект. Не превращать его в монстра. А так получается, что пришёл из ~~чёрного~~ мира всяких jade, где люди писали код маленькими порциями и радовались жизни. Про BEMJSON достаточно только в документации рассказать, а работать нужно СРАЗУ с BEMTREE!

Немного шрифт повысил, но я действительно вижу в этом большую проблему. Особенно когда вижу, что люди воспевают React и косятся при аббревиатуре БЭМ (что это только для "избранных").

**Comment by tadatuta** [comment]
Привет!

@belozyorcev, спасибо за инициативу! Было бы круто, если бы вместо одного issue с кучей несвязанных вопросов, было бы по одному отдельному на каждый вопрос. Тогда в комментах можно было обсуждать именно его.

Предлагаю исходный посыл про необходимость обсуждения унести на форум, а комментарии сконвертировать в отдельные issue. Сделаешь?

**Comment by belozyorcev** [comment]
@tadatuta ОК

**Comment by belozyorcev** [comment]
@tadatuta 

Тогда начало issue буду помечать собачкой @
