### ISSUE TITLE
После запуска npm start gulp перестает собирать проект.

### ISSUE THREAD

**Issue by serhioone** [bem/project-stub#179]
При сборке галпом после npm start то сборка падает
[https://monosnap.com/file/BbI9MXIPBYYHnkeQfwCoE0Jau5CGBp](url)

После удаления файлов сгенерированных enb  сборка начинает работать.

**Comment by skad0** [comment]
Тут возникает конфликт с созданным enb index.bemdecl.js, можешь его удалить из dekstop.bundles и сборка gulp'ом заработает.

**Comment by blond** [comment]
@skad0 конфликта возникать не должно, gulp должен либо брать BEMDECL, либо брать BEMJSON, но игнорить BEMDECL.

**Comment by skad0** [comment]
@blond тут проблема, что bem-decl еще не интегрирован в gulp-bem-bundler-fs и вместо его load используется просто чтение и nodeEval на полученном, без учета внутренностей. 
На днях займусь, вот [issue](https://github.com/gulp-bem/gulp-bem-bundler-fs/issues/5) по сути тот же самый.

**Comment by zxqfox** [comment]
Да, это скорее баг, чем конфликт.

@blond К слову, выходит, что он будет брать bemdecl.js для сборки, а bemjson.js для рендеринга html. И конфликт всё-таки будет, не знаю, надо ли его исправлять.

**Comment by skad0** [comment]
В следующей версии gulp-bem-bundler-fs будет работать
