### ISSUE TITLE
Yarn vs NPM

### ISSUE THREAD

**Issue by belozer** [bem/project-stub#192]
__Yarn__ очень понравился по скорости (__~ в 2 раза быстрей__ установка project-stub проходит). Его можно включить в README по установке __bem-starter-kit__ (project-stub) и как альтернативу использовать npm для установки пакетов старым способом. Изменений всего в несколько строчек.

В чём ещё плюс - __Yarn умеет работать offline__. После первой установки __bem-starter-kit__ пакеты кэшируются и последующие установки можно делать без доступа к сети.

**Comment by blond** [comment]
На наших проектах он не завёлся.

Я бы не стал его рекомендовать как годную альтернативу, пока основные ошибки не будут исправлены. Те, кому важна скорость могут использовать `Yarn` под свой страх и риск.

Если же мы будем рекомендовать `Yarn`, то должны как-то проверять, что устанавливаемые модули работают хорошо. Например, гонять тесты в Travis, используя и `Yarn` и `npm`.

А пока у нас нет никаких тестов в `project-stub`.

**Comment by belozer** [comment]
@blond а какие проблемы возникли и на каких версиях ярна?

**Comment by blond** [comment]
Пробовали на `v0.15.1`. Столкнулись как минимум с:

1. Не работает поддержка других registry (https://github.com/yarnpkg/yarn/issues/792).
2. Не работает установка пакетов из `git` репозиториев  (https://github.com/yarnpkg/yarn/issues/513).

Судя по ишьюсам там ещё много нюансов не учтено.

**Comment by a-x-** [comment]
в islands не возможно установка из-за строгого выполнения условия node engine, которая ограничена сверху в разных странных старых пакетах (https://github.com/yarnpkg/yarn/issues/1285#issuecomment-261904757)

**Comment by belozer** [comment]
В связи с последними версиями npm тему можно закрыть.

**Comment by a-x-** [comment]
... и увидеть тело проплывающего врага ...
