### ISSUE TITLE
Как gulp подружить с bemtree

### ISSUE THREAD

**Issue by Maksimenka** [bem/project-stub#210]
В исходном примере gulp файла создана реализация создания html  файла из bemjson + bemhtml. Как не пытался прикрутить bemtree ничего не вышло. 
Хотел сделать следующее:
bemdecl -> bemtree -> bemjson + bemhtml -> html

Возможно есть какие-нибудь примеры, был бы благодарен.

**Comment by ilyar** [comment]
Посмотри  это https://github.com/tadatuta/bem-bemtree-static-project-stub/commit/235de300b53a41d62c2410b934d3c059a5ad633b  подробности:

- https://github.com/bem-site/bem-forum-content-ru/issues/716
- https://github.com/tadatuta/bem-bemtree-static-project-stub/tree/one-bundle-gulp-watcher

**Comment by Maksimenka** [comment]
Видел, но там маловато общего с project-stub в направлении gulp.

**Comment by ilyar** [comment]
Портировал проект @tadatuta  посмотри [gulp: bemdecl -> bemtree + data -> bemjson + bemhtml -> html](https://github.com/ilyar/project-stub/commit/838ae018d67f476efd8f131ba6d48658eed07a07), надо только данные и блоки добавить, как описал Владимир, см. ссылки выше.

Еще на тему `gulp` есть: [Опыт внедрения gulp-bem](https://github.com/bem-site/bem-forum-content-ru/issues/1186) от @belozer, Сергей поделится интересным опытом и вполне рабочим решением.

И может быть будет полезно, интересно и познавательно: [enb: bemdecl -> bemtree + data -> bemjson + bemhtml -> html](https://github.com/ilyar/project-stub/commit/a5cb3f8fd67e95f821a1acd199905c2692802a3c). Есть небольшое отличение, данные берутся из папки бандла `*.data.js`

**Comment by ilyar** [comment]
Да еще у решения с `enb` есть особенность в том, там добавлена технология `bemtree-to-bemjson`, а  сборка `bemtree` уже была, только надо было раскомментировать. В результате получаем промежуточный результат в виде `bemjson`, а конечный `html` получаем тем же конфигом без дополнительных изменений.

Так делать было не обязательно можно, как описал Владимир воспользоваться технологией `bemtree-to-html`, но мне так показалось интереснее.

**Comment by Maksimenka** [comment]
Спасибо, буду пробовать.
