### ISSUE TITLE
Не работает команда создания блока

### ISSUE THREAD

**Issue by nicothin** [bem/project-stub#215]
https://github.com/bem/project-stub/blob/master/README.ru.md#Создание-блока
Выполнил `npm i ym --save-dev`
Пишу `bem create -l desktop.blocks -b layout -T css`
Получаю
```
  Usage: bem [options] [command]


  Commands:

    make [options]     build specified targets
    server [options]   run development server
    *                

  Options:

    -h, --help     output usage information
    -V, --version  output the version number
```
Папка блока не создаётся.
Возможно, связано с https://github.com/bem/project-stub/issues/132

**Comment by tadatuta** [comment]
Предположу, что либо ревизия `project-stub` старая, либо устарели `npm`-зависимости, т.к. мы обновили `bem-tools` какое-то время назад (см. https://github.com/bem/project-stub/commit/caf35d075fe38c6f97b1bb3057b93a22d316f2f4).

**Comment by nicothin** [comment]
@tadatuta клонировал сегодня (уже вчера), зависимости ставил сегодня :(
это я на маке пробовал

сейчас поставил зависимости на винду:
```
$ bem create -l desktop.blocks -b layout -T css
bash: bem: command not found
```
но `./node_modules/.bin/bem create -l desktop.blocks -b layout -T css` отработала нормально.

Попробую на маке переставить зависимости.

**Comment by tadatuta** [comment]
Еще вариант: в системе глобально установлена старая версия `bem-tools` и при запуске `bem create` вызывается именно она вместо локальной.

**Comment by tadatuta** [comment]
А чтобы не писать целиком `./node_modules/.bin/bem` вместо `bem` стоит добавить в переменную окружения `PATH` вот такое: `./node_modules/.bin`.

**Comment by nicothin** [comment]
Да, в системе стояла старая bem-cli.
