### ISSUE TITLE
баг в последней версии

### ISSUE THREAD

**Issue by bardak-dev** [bem/project-stub#256]
любой контент оборачивается в двойные кавычки и невозможно выводить html внутри контента
пример кода (на чистом клоне)
```javascript
 content: [
        {
            block: 'header',
            content: [
                'header content goes here'
            ]
        },
        {
            block : 'image',
            content : '<svg xmlns="http://www.w3.org/2000/svg" width="15" height="16"><path d="M13.5.5l-8 12L1.7 8l-1 1.6L5.6 15l9.1-13.4z"/></svg>'
        },
        {
            block : 'bem',
            content : '<br><br>BEM WTF?<br><br>'
        },
        {
            block: 'footer',
            content: [
                'footer content goes here'
            ]
        }
    ]
```
на странице будет:
![Screenshot](http://pix.my/o/lAdw3Q)

**Comment by tadatuta** [comment]
@bardak-dev Это не баг, это фича! :)

В новой версии включено экранирование в шаблонизаторе по умолчанию. Соответственно есть 2 опции:
1. Отключить его (может быть опасно, если есть пользовательский ввод данных)
2. Использовать `{ content: { html: 'здесь HTML не будет экранироваться' } }` там, где нужно вывести разметку как есть.

Подробнее см. https://github.com/bem/bem-xjst/blob/master/docs/ru/3-api.md#%D0%AD%D0%BA%D1%80%D0%B0%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5
