### ISSUE TITLE
HTML string from bemjson is converted to text

### ISSUE THREAD

**Issue by rteamx** [bem/project-stub#273]
In bemjson:
``` js
{
  block: 'some',
  content: 'Text<br/>text2'
}
```

Result in html some times ago: 
``` html
<div class="some">Text<br/>text2</div>
```

Result in html now 
``` html
<div class="some">Text&lt;br&gt;Text</div>
```

**Comment by tadatuta** [comment]
@rteamx that's because of new default value for escaping in `bem-xjst 8.x`.
you may switch it off with https://github.com/bem/bem-xjst/blob/master/docs/en/3-api.md#escaping or use `html` field to render some particular nodes without escaping:
```js
{
    block: 'some',
    content: {
        html: 'Text<br/>text2'
    }
}
```

**Comment by rteamx** [comment]
@tadatuta oh, i see. Thanks!
