### ISSUE TITLE
Проблемы установки из коробки

### ISSUE THREAD

**Issue by pavelpower** [bem/project-stub#73]
Так, как большинство технологий используемых в данном проекте нет у большинства разработчиков, которые хотят попробовать на зубок, просто нет. То нужно учитывать это.

Я дал задание двум бойцам попробовать этот проект и они столкнулись с проблемами, которые решались только так:

* clone project:
```bash
git clone https://github.com/bem/project-stub.git -b bem-core my-bem-project
cd my-bem-project
npm install
```

* install another libs
```bash
npm install stylus -g
npm install bower -g
npm install travis-ci # not necessarily
npm install q-io
```

* install package for libs
```bash
cd libs/bem-components && npm install && bower install
cd ../bem-core &&  && npm install && bower install
```

4. run server `bem server -p 8080 -v debug`

@arikon Подсказал, что с установкой должен помочь `bower-npm-install` пакет. Но его нет в основных зависимостях. И людям не ведомо за него.

**Comment by tadatuta** [comment]
@innabelaya Инна, давай добавим в quick start предупреждение, что не стоит устанавливать npm- и bower-пакеты под `root`?

**Comment by just-boris** [comment]
@tadatuta FYI, bower из-под root не запускается: https://github.com/bower/bower/blob/master/lib/util/rootCheck.js#L24

**Comment by tadatuta** [comment]
@just-boris для этого есть флаг `--allow-root`, но да, речь как раз о том, чтобы не рекомендовать пользователям такой способ
