### ISSUE TITLE
А что если выкладывать на gh-pages результат сборки бандла index?

### ISSUE THREAD

**Issue by eGavr** [bem/project-stub#98]
Будем сразу показывать,  что можно получить, если собрать проект.

**Comment by Guria** [comment]
команда которая будет коммитить в ветку gh_pages была бы весьма полезна

**Comment by tadatuta** [comment]
@eGavr  В `project-stub` не предполагается чего-либо, что имеет смысл показывать.

@Guria `git push origin gh-pages` ;)

**Comment by eGavr** [comment]
Ну а как же бандл,  который соберется?) И как бы уже показываем всю красоту, возможности библиотек)

**Comment by Guria** [comment]
@tadatuta вообщето:
```bash
$ git checkout --orphan gh-pages
$ rm -rf *
$ git rm --cached *
$ touch index.html
$ git add index.html
$ git commit -m "Seed publish branch for GitHub Pages"
$ git push origin gh-pages
```
Ну естественно коммитить надо будет результат сборки, а не пустой index.html

**Comment by Guria** [comment]
Я говорю про команду, которая обладая знаниями о том какие артефакты публикуются, сама сделает всю рутину.
Правда есть ещё проблема. Кажется, gh-pages не отдают файлы, которые начинаются с символа `_`.

**Comment by tadatuta** [comment]
@eGavr 
`project-stub` задуман именно как такой репозиторий, с которого можно очень быстро начать делать свой проект, он не про демонстрацию возможностей библиотек или инструментов. Т.е. да, витрина нужна и мы будем ее делать на базе библиотек блоков, но в `project-stub` не хочется иметь ничего, что не требуется в среднестатистическом проекте.

@Guria 
Это слишком частный случай. Опять же, можно сделать отдельный проект, который будет уметь деплоить статику на gh-pages (кстати, это удобно делать автоматически на `travis` на каждый коммит в `master`), но не хочется считать это каким-то «рекомендованным» способом.

Если интересно, то вот пример такого проекта: https://github.com/tadatuta/bb (см. `.travis.yml` и `update-gh-pages.sh`).

> gh-pages не отдают файлы, которые начинаются с символа `_`.

достаточно положить пустой файл `.nojekyll`

**Comment by eGavr** [comment]
исчерпывающий ответ :+1:
